# Site settings
title: Course Website
subtitle: Title of the Course
description: |
    Add a description of your course.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/eugkenny/course-website" # the base hostname & protocol for your site
syllabus: "/syllabus"
githubdir: "eugkenny/course-website"

# Author/user information
email: eugkenny.lit@gmail.com
twitter_username: 
github_username:  eugkenny
authorurl: "https://eugkenny.github.io"
address: |
    Department of Information Technology
    Limerick Instutute of Technology (Thurles Campus)

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
